// flow-typed signature: d7398491fa184d4ff55938bca9a2228b
// flow-typed version: <<STUB>>/byline_v5.x/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'byline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'byline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'byline/lib/byline' {
  declare module.exports: any;
}

// Filename aliases
declare module 'byline/lib/byline.js' {
  declare module.exports: $Exports<'byline/lib/byline'>;
}
