// flow-typed signature: 05f3f0a91b6edb11ba985324b7bb68fe
// flow-typed version: <<STUB>>/jsdoc-babel_v0.3.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdoc-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdoc-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdoc-babel/lib/index' {
  declare module.exports: any;
}

declare module 'jsdoc-babel/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdoc-babel/lib/index.js' {
  declare module.exports: $Exports<'jsdoc-babel/lib/index'>;
}
declare module 'jsdoc-babel/src/index.js' {
  declare module.exports: $Exports<'jsdoc-babel/src/index'>;
}
