// flow-typed signature: 3ea9f434a203b507c408250c1d1b4641
// flow-typed version: <<STUB>>/line-by-line_v0.1.4/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'line-by-line'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'line-by-line' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'line-by-line/examples/example' {
  declare module.exports: any;
}

declare module 'line-by-line/line-by-line' {
  declare module.exports: any;
}

// Filename aliases
declare module 'line-by-line/examples/example.js' {
  declare module.exports: $Exports<'line-by-line/examples/example'>;
}
declare module 'line-by-line/line-by-line.js' {
  declare module.exports: $Exports<'line-by-line/line-by-line'>;
}
